main: fr.fingarde.mineandglory.Main
name: MineAndGlory
version: 1.0
description: Plugin for MineAndGlory
author: Fingarde
api-version: 1.13
commands:
  enderchest:
    aliases:
      - ec
    description: Ouvre l'ender chest
  feed:
      description: Nourrit un joueur
  heal:
      description: Soigne un joueur
  god:
    description: Rend un joueur invulnerable
  cgive:
    description: Give