main: fr.fingarde.mineandglory.Main
name: MineAndGlory
version: 1.0
description: Plugin for MineAndGlory
author: Fingarde
api-version: 1.13
commands:
  enderchest:
    aliases:
      - ec
    description: Ouvre l'ender chest
  feed:
      description: Nourrit le joueur
  heal:
      description: Soigne le joueur
  cgive:
    description: Give